version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: "http://127.0.0.1:8000"
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
