# Generated by Django 4.2.10 on 2024-06-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_alter_product_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetlog",
            name="asset_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="assetlog",
            name="asset_owner",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="assetlog",
            name="asset_serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="assetlog",
            name="asset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.asset",
            ),
        ),
    ]
