# Generated by Django 4.2.10 on 2024-06-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_assetlog_asset_name_assetlog_asset_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assetlog",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
