# Generated by Django 4.2.10 on 2024-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_alter_assetlog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetlog",
            name="user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
