# Generated by Django 4.2.10 on 2024-06-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_alter_assetlog_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assetlog",
            old_name="user",
            new_name="username",
        ),
    ]
