# Generated by Django 4.2.10 on 2024-05-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
