# Generated by Django 4.2.10 on 2024-05-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_institution_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
