# Generated by Django 4.2.10 on 2024-06-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_otp_user_otp_expiration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institution",
            old_name="usernane",
            new_name="username",
        ),
    ]
