# Generated by Django 4.2.10 on 2024-06-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_usernane_institution_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="status",
            field=models.CharField(default="New", max_length=100),
        ),
    ]
