# Generated by Django 4.2.10 on 2024-06-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_institution_status_alter_user_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="changed_password",
            field=models.BooleanField(default=False),
        ),
    ]
