# Generated by Django 4.2.10 on 2024-06-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_institution_changed_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="changed_password",
        ),
        migrations.AddField(
            model_name="user",
            name="changed_password",
            field=models.BooleanField(default=False),
        ),
    ]
